[backend]
type = "paramstore"
prefix = "/myapp"
region = "your-aws-region"
access_key = "{{ getenv `ACCESS_KEY` }}"
secret_key = "{{ getenv `SECRET_KEY` }}"

[template]
src = "templates/config.php.tmpl"
dest = "config.php"
keys = [
  "/database/host",
  "/database/port",
  "/database/username",
  "/database/password"
]
 
