name: Confd Parameter Store

on:
  push:
    branches:
      - main
      

jobs:
  build:
      runs-on: ubuntu-latest
  using-environments :
       runs-on: ubuntu-latest
       environment:
           name : dev
       steps:
         - name: Checkout repository
           uses: actions/checkout@v2
          
         - name: Clone
           run: echo ${{ secrets.NAME }}
                
          
