name: Upload to S3 and Invalidate CloudFront

on :
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CONFIG_VARIABLE: ${{ env.CONFIG_VARIABLE_BASE }}
    steps:
      - name: Use environment variables
        run: |
          echo $CONFIG_VARIABLE


