name: Confd Parameter Store

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          # Install confd
          # Install AWS CLI or configure AWS SDK

      - name: Configure AWS CLI or SDK
        run: |
          aws configure set aws_access_key_id ${{ secrets.ACCESS_KEY }}
          aws configure set aws_secret_access_key ${{ secrets.SECRET_KEY }}
          aws configure set default.region eu-north-1

      - name: Generate configuration file
        run: |
          confd -confdir ./confd -onetime -backend paramstore

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add config.php
          git commit -m "Update config.php by GitHub Actions"
          git push
