name: Upload to S3 and Invalidate CloudFront

on:
   workflow_dispatch:  
      inputs:
        environment:
           description: 'Environment'
           required: true
           default: 'dev'
jobs:
   Artifacts_copy:
    runs-on: ubuntu-latest
    

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Load environment variables
        run: |
              if [ "${{ inputs.environment }}" == "dev" ]; then
                 echo "Loading dev environment variables"
                 set -a && source /home/runner/work/_temp/dev.env && set +a
               else
                  echo "Environment not specified or unsupported"
                  exit 1
               fi
      - name: Checkout repository
        run: |
             echo $NAME
   
